all:
	g++  Tank.cpp Tank.h Boat.h Boat.cpp Car.h Car.cpp Factory.cpp Factory.h FactoryAtSea.h FactoryAtSea.cpp FactoryOnLand.cpp FactoryOnLand.h IVehicle.h Main.cpp Main.h SteamShip.cpp SteamShip.h Vehicle.h -o main
clean:
	rm ./main
