all:
	 g++ Main.cpp Main.h IFactory.h IFactory.cpp MacFactory.cpp MacFactory.h MacPropertype.cpp MacPropertype.h MacProduct.h MacProduct.cpp IProduct.cpp IProduct.h IPropertype.cpp IPropertype.h WinFactory.cpp WinFactory.h WinProduct.cpp WinProduct.h WinPropertype.cpp WinPropertype.h -o main
clean:
	rm ./main