all: 
	g++ main.h main.cpp Prototype.h Type.h Prototype.cpp ConcretePrototypeA.h ConcretePrototypeA.cpp ConcretePrototypeB.h ConcretePrototypeB.cpp PrototypeFactory.h PrototypeFactory.cpp -o main
clean:
	rm ./main